pipeline:
  docker:
    image: plugins/docker
    registry: quay.io
    repo: quay.io/natlibfi/drone-gen-tags
    environment:
    - DOCKER_CONTENT_TRUST=1
    secrets:
    - docker_username
    - docker_password
    - docker_content_trust_root_passphrase
    - docker_content_trust_repository_passphrase
    when:
      event: [push]
branches: [master]
