pipeline:
  docker:
    image: plugins/docker
    registry: quay.io
    repo: quay.io/natlibfi/drone-gen-tags
    secrets:
    - docker_username
    - docker_password
    when:
      event: [push]
branches: [feature/better-tagging]
